### ISSUE TITLE
The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll.

### ISSUE THREAD

**Issue by marcogaio** [stefankueng/demohelper#11]
I've just upgraded from 1.3.0 to 2.1.0, and now refuse to start with this error.

OS Win7 64bit.

Thanks.

**Comment by stefankueng** [comment]
Win7 has reached its end of life almost a year ago and therefore isn't supported anymore.

**Comment by marcogaio** [comment]
Ops, ok... i've totally missed 'demohelper require windows 8 or later' banner, sorry. And thanks.
