### ISSUE TITLE
Add colors for background dark 

### ISSUE THREAD

**Issue by iberck** [stefankueng/demohelper#7]
Colors look dull on a black background:

[Example](https://www.evernote.com/l/AQIO2GTyAP1GQaqx9hdDYB7gs25Nksvoz0s/)

**Comment by stefankueng** [comment]
The default is for the colors to draw with a little transparency so when you draw the content below is still visible.
To make the colors opaque, press the 'T' key.

**Comment by iberck** [comment]
thank you ! works perfect
