### ISSUE TITLE
Save last used values (line thickness, colors, ...) and use it on next start

### ISSUE THREAD

**Issue by warrengay** [stefankueng/demohelper#8]
It would be great to be able to change the thickness of the lines, either in config or at runtime via shortcut keys.

**Comment by stefankueng** [comment]
![image](https://user-images.githubusercontent.com/665591/94984510-0c2f9e00-054d-11eb-842b-06fc9e944809.png)

I think that's what you're looking for?

**Comment by warrengay** [comment]
Great, thanks Stefan! I must have missed this in the documentation.

Is there anyway of permanently fixing the size?

**Comment by stefankueng** [comment]
No, but how about saving the last used value and use it on the next start?
It's my opinion that settings should be kept to a minimum...

**Comment by warrengay** [comment]
That would be great but how do you save the size? Everytime I restart it
starts from the smallest pen size?

**Comment by stefankueng** [comment]
that will be done automatically in the next version

**Comment by warrengay** [comment]
Excellent, thanks! When do you expect the next version to be ready?

Thanks for such a great tool by the way!

**Comment by stefankueng** [comment]
not sure when I have enough time for a new release, but I hope sometime next week.
Hope that's ok.
